---
- name: Tomcat deployment playbook
  hosts: 'all'
  become: yes
  become_method: sudo
  tasks:
    - name: Update all packages
      apt:
        name: "*"
        state: latest

    - name: Install Java
      apt:
        name: openjdk-8-jdk
        state: present

    - name: Add tomcat group
      group:
        name: tomcat

    - name: Add "tomcat" user
      user:
        name: tomcat
        group: tomcat
        home: /usr/share/tomcat
        createhome: no
        system: yes

    - name: Download Tomcat
      get_url:
        url: https://archive.apache.org/dist/tomcat/tomcat-9/v9.0.75/bin/apache-tomcat-9.0.75.tar.gz
        dest: /tmp/apache-tomcat-9.0.75.tar.gz

    - name: Create a tomcat directory
      file:
        path: /usr/share/tomcat
        state: directory
        owner: tomcat
        group: tomcat

    - name: Extract tomcat archive
      unarchive:
        src: /tmp/apache-tomcat-9.0.75.tar.gz
        dest: /usr/share/tomcat
        owner: tomcat
        group: tomcat
        remote_src: yes
        extra_opts: "--strip-components=1"
        creates: /usr/share/tomcat/bin

    - name: Copy tomcat service file
      template:
        src: tomcat.service.j2
        dest: /etc/systemd/system/tomcat.service
   
    - name: Start and enable tomcat
      service:
        daemon_reload: yes
        name: tomcat
        state: started
        enabled: yes

    - name: Start and enable firewalld
      service:
        name: firewalld
        state: started
        enabled: yes
        
    - name: Open tomcat port on the firewall
      firewalld:
        port: 8080/tcp
        permanent: true
        state: enabled
        immediate: yes

  handlers:
    - name: restart tomcat
      service:
        name: tomcat
        state: restarted
